FROM python:3.12-slim

RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker

# Add code location code
WORKDIR /opt/dagster/app
COPY dagsterdemo/ /opt/dagster/app/dagsterdemo
COPY dagsterdemo_tests/ /opt/dagster/app/dagsterdemo_tests

# Run dagster code server on port 4000
EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors to execute runs and steps
CMD ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-f", "dagsterdemo/definitions.py"]